---
dist:     bionic

# # language: python
language: generic
# language: minimal

sudo: required

services:
 - docker

env:
    global:
        DEBIAN_FRONTEND="noninteractive"

install:
  - docker-compose --version
  - docker         --version

script:
  - make --version
  - bash -c "make --version"

  - bash -c "make build-alpine"
  - bash -c "make build-ubuntu"
  # - bash -c "make build-deb"

  - bash -c "make test-alpine"
  - bash -c "make test-ubuntu"
  # - bash -c "make test-deb"
