---
language: python

sudo: required

services:
 - docker

env:
    global:
        DEBIAN_FRONTEND="noninteractive"

install:
  - docker-compose --version
  - docker         --version

script:
  - make alpine
  - make ubuntu
  - make deb
  - make test-alpine
  - make test-ubuntu
  - make test-deb
